---
- !ruby/object:Rubber::Configuration::InstanceItem
  name: web01
  domain: chef-client.cin.ufpe.br
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: passenger
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: apache
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem
    name: postgresql
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: postgresql_master
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  instance_id: web01
  image_type: 
  image_id: 
  security_groups:
  - default
  zone: 
  network: 
  gateway: 
  external_host: 
  external_ip: chef-client.cin.ufpe.br
  internal_host: 
  internal_ip: 172.21.6.102
  provider: generic
  platform: linux
  root_device_type: 
- volumes: {}
  static_ips: {}
  vpc: {}
